Repository JejuislandToyProject/JejuIsland, pull requests merged in 2021-10, with the labels that each got.

#10 Feature/8 login UI db
  JeJu/src/main/java/com/kgitbank/jeju/controller/LoginController.java
  JeJu/src/main/java/com/kgitbank/jeju/dto/User.java
  JeJu/src/main/java/com/kgitbank/jeju/login/KakaoLoginBO.java
  JeJu/src/main/java/com/kgitbank/jeju/login/NaverLoginBO.java
  JeJu/src/main/java/com/kgitbank/jeju/mapper/UserMapper.java
  JeJu/src/main/java/com/kgitbank/jeju/service/LoginService.java
  JeJu/src/main/java/com/kgitbank/jeju/service/impl/LoginServiceImpl.java
  JeJu/src/main/resources/com/kgitbank/jeju/mapper/UserMapper.xml
  JeJu/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: enhancement

#25 mypage ui
  JeJu/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  JeJu/src/main/webapp/resources/css/jquery-sakura.css
  JeJu/src/main/webapp/resources/css/mypage.css
  JeJu/src/main/webapp/resources/img/img/icon1.PNG
  JeJu/src/main/webapp/resources/img/img/jejuimg1.PNG
  JeJu/src/main/webapp/resources/js/jquery-sakura.js
Labels: enhancement

#26 change some UI
  JeJu/src/main/webapp/WEB-INF/views/index.jsp
Labels: enhancement

#27 Feature/19 mypage db
  JeJu/src/main/java/com/kgitbank/jeju/controller/JejuController.java
  JeJu/src/main/java/com/kgitbank/jeju/controller/MyPageRestController.java
  JeJu/src/main/java/com/kgitbank/jeju/dto/FamousRestaurant.java
  JeJu/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  JeJu/src/main/webapp/resources/css/mypage.css
  JeJu/src/main/webapp/resources/img/icon1.PNG
  JeJu/src/main/webapp/resources/img/jejuimg1.PNG
  JeJu/src/main/webapp/resources/js/jquery.twbsPagination.min.js
  JeJu/src/main/webapp/resources/js/mypage.js
Labels: bug, duplicate, enhancement

#33 Feature/32 naver login error
  JeJu/src/main/java/com/kgitbank/jeju/controller/LoginController.java
  JeJu/src/main/java/com/kgitbank/jeju/login/NaverLoginBO.java
Labels: bug

#100 logout button add & admin side bar UI 수정 #99
  JeJu/src/main/webapp/WEB-INF/views/admin/admin.jsp
  JeJu/src/main/webapp/resources/css/admin.css
Labels: enhancement
