Repository JejuislandToyProject/JejuIsland, pull requests merged in 2021-11, with the labels that each got.

#104 duplicate/#94 TravelCourse css update_수정버전
  JeJu/src/main/webapp/resources/css/courseCSS/button.css
  JeJu/src/main/webapp/resources/css/courseCSS/leftSection.css
  JeJu/src/main/webapp/resources/css/courseCSS/main.css
  JeJu/src/main/webapp/resources/css/courseCSS/modal.css
  JeJu/src/main/webapp/resources/css/courseCSS/rightSection.css
  JeJu/src/main/webapp/resources/js/courseJS/cardAddAndDelete.js
  JeJu/src/main/webapp/resources/js/courseJS/createCard.js
Labels: duplicate

#106 duplicate/#105-course.jsp update
  JeJu/src/main/webapp/WEB-INF/views/travelCourse/course.jsp
Labels: duplicate

#108 duplicate/#107-button.css class name update
  JeJu/src/main/webapp/resources/css/courseCSS/button.css
Labels: duplicate

#110 admin logout button 수정
  JeJu/src/main/webapp/resources/css/admin.css
Labels: documentation

#114 Feature/23 main UI
  JeJu/src/main/java/com/kgitbank/jeju/controller/JejuController.java
  JeJu/src/main/java/com/kgitbank/jeju/mapper/FamousRestaurantMapper.java
  JeJu/src/main/java/com/kgitbank/jeju/mapper/TouristSpotMapper.java
  JeJu/src/main/java/com/kgitbank/jeju/service/MainService.java
  JeJu/src/main/java/com/kgitbank/jeju/service/impl/MainServiceImpl.java
  JeJu/src/main/resources/com/kgitbank/jeju/mapper/FamousRestaurantMapper.xml
  JeJu/src/main/resources/com/kgitbank/jeju/mapper/TouristSpotMapper.xml
  JeJu/src/main/webapp/WEB-INF/views/board/form.jsp
  JeJu/src/main/webapp/WEB-INF/views/board/restaurantForm.jsp
  JeJu/src/main/webapp/WEB-INF/views/index.jsp
  JeJu/src/main/webapp/resources/css/cssmodal.css
  JeJu/src/main/webapp/resources/css/index.css
  JeJu/src/main/webapp/resources/css/styles.css
  JeJu/src/main/webapp/resources/js/js모달.js
Labels: duplicate, enhancement

#117 Feature/86 admin nav fix
  JeJu/src/main/java/com/kgitbank/jeju/controller/JejuController.java
  JeJu/src/main/webapp/WEB-INF/views/admin/admin.jsp
  JeJu/src/main/webapp/WEB-INF/views/admin/utilities-site.jsp
  JeJu/src/main/webapp/WEB-INF/views/admin/utilities-user-ban.jsp
  JeJu/src/main/webapp/resources/css/admin.css
Labels: bug, duplicate, design

#119 Feature/32 login
  JeJu/src/main/webapp/WEB-INF/views/index.jsp
  JeJu/src/main/webapp/resources/css/index.css
  JeJu/src/main/webapp/resources/img/course-illustration.svg
Labels: duplicate, design

#120 feature/redesign logo
  JeJu/src/main/webapp/WEB-INF/views/index.jsp
  JeJu/src/main/webapp/WEB-INF/views/login/login.jsp
  JeJu/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  JeJu/src/main/webapp/WEB-INF/views/travelCourse/course.jsp
  JeJu/src/main/webapp/resources/css/courseCSS/main.css
  JeJu/src/main/webapp/resources/css/index.css
  JeJu/src/main/webapp/resources/css/mypage.css
  JeJu/src/main/webapp/resources/css/styles.css
Labels: duplicate, design

#128 Feature/fix error
  JeJu/src/main/java/com/kgitbank/jeju/controller/CourseRestController.java
  JeJu/src/main/webapp/WEB-INF/views/index.jsp
  JeJu/src/main/webapp/resources/css/courseCSS/button.css
  JeJu/src/main/webapp/resources/css/courseCSS/leftSection.css
  JeJu/src/main/webapp/resources/css/courseCSS/main.css
  JeJu/src/main/webapp/resources/css/courseCSS/rightSection.css
  JeJu/src/main/webapp/resources/css/index.css
  JeJu/src/main/webapp/resources/js/courseJS/createCard.js
Labels: design

#127 좌측상단 관리자 페이지 링크 페이지 미적용 수정
  JeJu/src/main/webapp/WEB-INF/views/admin/admin.jsp
  JeJu/src/main/webapp/WEB-INF/views/admin/utilities-site.jsp
  JeJu/src/main/webapp/WEB-INF/views/admin/utilities-user-ban.jsp
Labels: bug

#129 delete remember me button
  JeJu/src/main/webapp/WEB-INF/views/admin/adminLogin.jsp
Labels: design

#132 delete text
  JeJu/src/main/webapp/WEB-INF/views/index.jsp
Labels: design

#134 change side bar height
  JeJu/src/main/webapp/resources/css/courseCSS/leftSection.css
  JeJu/src/main/webapp/resources/css/courseCSS/rightSection.css
Labels: design

#135 Feature/fix error
  JeJu/src/main/java/com/kgitbank/jeju/controller/MyPageRestController.java
  JeJu/src/main/java/com/kgitbank/jeju/controller/RestaurantContoller.java
  JeJu/src/main/java/com/kgitbank/jeju/controller/TouristController.java
  JeJu/src/main/java/com/kgitbank/jeju/mapper/TouristSpotMapper.java
  JeJu/src/main/java/com/kgitbank/jeju/service/impl/BoardServiceImpl.java
  JeJu/src/main/resources/com/kgitbank/jeju/mapper/FamousRestaurantMapper.xml
  JeJu/src/main/resources/com/kgitbank/jeju/mapper/TouristSpotMapper.xml
  JeJu/src/main/webapp/WEB-INF/views/board/restaurantBoard.jsp
  JeJu/src/main/webapp/WEB-INF/views/board/touristBoard.jsp
Labels: bug, enhancement
